source 'https://rubygems.org'

gem "sinatra"
gem "activerecord"
gem "sinatra-activerecord"
gem 'rake'
gem 'sqlite3'

=begin
group :development do
 gem 'sqlite3'
end

group :production do
 gem 'sqlite3'
end
=end
